server:
  port: 8080
  environment: DEVELOPMENT

spring:
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/evotingapp
    username: postgres
    password: evotingapp
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    group: true
    baseline-on-migrate: true
    user: postgres
    password: evotingapp
    baseline-description: "init"
    baseline-version: 1.1