application:
  jwt:
    access-token-expiration-seconds: 129600 #36h
    refresh-token-expiration-seconds: 604800 #7d
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/evotingapp
    username: postgres
    password: evotingapp
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    group: true
    baseline-on-migrate: true
    user: postgres
    password: evotingapp
    baseline-description: "Change id data types to bigint"
    baseline-version: 1.7