application:
  base-url: ${BASE_URL}
  path: ./
  allow-origin: ${BASE_URL}
  jwt:
    access-token-expiration-seconds: 900 #15min
    refresh-token-expiration-seconds: 604800 #7d
  security:
    password-reset-token-expiration-seconds: 300 #5min
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_DB_HOST}:${POSTGRESQL_DB_PORT}/${POSTGRESQL_DB_NAME}
    username: ${POSTGRESQL_DB_USERNAME}
    password: ${POSTGRESQL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mail:
    smtp:
      starttls:
        enable: true
      auth: true
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from:
      email: ${MAIL_USERNAME}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    group: true
    baseline-on-migrate: true
    user: postgres
    password: evotingapp
    baseline-version: 1.8