application:
  jwt:
    access-token-expiration-seconds: 3600
    refresh-token-expiration-seconds: 7200

spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/evotingapp
    username: postgres
    password: evotingapp
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    group: true
    baseline-on-migrate: true
    user: postgres
    password: evotingapp
    baseline-description: "Add groups"
    baseline-version: 1.6